

<table border="0" width="100%" cellspacing="0" cellpadding="0">
  <tbody>
    <tr>

      <td style="padding:0px 0px 0px 0px" valign="top" width="100%" rowspan="1" colspan="1" align="center">

        <table border="0" width="100%" cellspacing="0" cellpadding="0">
          <tbody>
            <tr>
              <td style="color:#454545;font-family:Arial,Helvetica,sans-serif;font-size:10pt;padding:8px 32px 9px 32px" valign="top" rowspan="1" colspan="1" align="left">

                <div>
                  <br> 
                  <p style="text-align:justify;text-justify:inter-word;">Dear Dr. <?php echo $this->name?>,</p> 

                  <p style="text-align:justify;text-justify:inter-word;">Thank you for your interest in the use of the Virtual Microscope application for your digital slides. </p>

                    <p style="text-align:justify;text-justify:inter-word;">We are excited about this new feature and hope you like at much as we do. The project is currently in 
                    pilot phase , so if you encounter issues or have suggestions for improvement, please let us know !</p>

                    <p style="text-align:justify;text-justify:inter-word;">As part of slide publication process you are requested to upload your high resolution slides through 
                    a Virtual Microscope account that we have created for you. You can login into this account at 

                    <a target="_blank" style="color:#ee5624;font-family:Arial,Helvetica,sans-serif;font-weight:bold;font-size:10pt"  href="http://elseviervm.kitware.fr/elsevierdp">elseviervm.kitware.fr/elsevierdp</a>. The login will be
                     <?php if($this->isjournal)echo "the EES  submission number";?> <b><?php echo $this->login?></b> and the 

                    password is <b><?php echo $this->password?></b>. 
                    </p>
                    <p>
                    For any support issues, please contact <a style="color:#ee5624;font-family:Arial,Helvetica,sans-serif;font-weight:bold;font-size:10pt"  target="_blank" href="mailto:<?php echo $this->contactEmail?>"><?php echo $this->contactEmail?></a>. 
                    </p>

                    <p style="text-align:justify;text-justify:inter-word;">OSEHRA Technique Journal.</p>
                <br/>
                
              </td>
            </tr>
          </tbody>
        </table>


      </td>

    </tr>
  </tbody>
</table>
