

<table border="0" width="100%" cellspacing="0" cellpadding="0">
  <tbody>
    <tr>

      <td style="padding:0px 0px 0px 0px" valign="top" width="100%" rowspan="1" colspan="1" align="center">

        <table border="0" width="100%" cellspacing="0" cellpadding="0">
          <tbody>
            <tr>
              <td style="color:#454545;font-family:Arial,Helvetica,sans-serif;font-size:10pt;padding:8px 32px 9px 32px" valign="top" rowspan="1" colspan="1" align="left">

                <div>
                  <br>
                  <p style="text-align:justify;text-justify:inter-word;">Dear Editor/Administrator,</p>

                  <p style="text-align:justify;text-justify:inter-word;">A new article is just submitted to OSEHRA Technique Journal pending for approval. </p>

                    <p style="text-align:justify;text-justify:inter-word;">Please take time to review the submission and publish it when it is ready!</p>

                    <p style="text-align:justify;text-justify:inter-word;">OSEHRA Technique Journal.</p>
                <br/>
              </td>
            </tr>
          </tbody>
        </table>


      </td>

    </tr>
  </tbody>
</table>
